# Generated by Django 5.2.9 on 2025-12-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='完了済み'),
        ),
    ]
