# Generated by Django 5.2.9 on 2025-12-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_is_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='parent_todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_todo', to='main.todo'),
        ),
    ]
