# Generated by Django 5.2.9 on 2026-01-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_todo_parent_todo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='todo',
            name='rank_range_check',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='parent_todo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='rank',
        ),
    ]
